-- Create SQL Database to store the data: FFIEC_CDR_CALL_PUBLIC

DROP DATABASE IF EXISTS "FFIEC_CDR_CALL_PUBLIC";

CREATE DATABASE "FFIEC_CDR_CALL_PUBLIC"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;